version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    networks: 
      - assembleia-network
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    networks: 
      - assembleia-network
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  mysqlsrv:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "assembleia"
    ports:
      - "3306:3306"
    volumes:
      - ./Docker/volumes/MySql:/var/lib/mysql
    networks:
      - assembleia-network

  assembleiasrv:
    build:
      context: .
      dockerfile: Dockerfile
    image: assembleia-api 
    networks: 
      - assembleia-network
    depends_on:
      - kafka
      - mysqlsrv
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqlsrv:3306/assembleia?useLegacyDatetimeCode=false&serverTimezone=America/Recife
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_KAFKA_BOOTSTRAP-SERVERS=kafka:29092
    ports:
      - 8081:8081 

networks: 
  assembleia-network:
    driver: bridge  